apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
- controller-cfg.yaml
images:
- name: quay.io/samba.org/samba-operator
  newName: localhost:5000/smb-operator
  newTag: latest
